---

- name: download oracle jdk
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jre-8u111-linux-x64.rpm
    headers: 'Cookie: oraclelicense=accept-securebackup-cookie'
    dest: /tmp/oracle-jre.rpm

- name: install the nginx rpm from a remote repo
  yum:
    name: /tmp/oracle-jre.rpm
    state: present

- lineinfile: dest=/home/hadoop/.bashrc regexp="^export JAVA_HOME" line="export JAVA_HOME=/usr/java/jre1.8.0_111"
